// AUTO-GENERATED by scripts/fsm_harness_split.py (Section 7 -- Build 980)
// THIS FILE IS AN AUDIT REFERENCE ONLY -- NOT COMPILED.
// Verify against src/ originals before any harness changes.
// -----------------------------------------------------------------------

// === BLOCK 1: FollowerReplaceState enum (V12_002.cs L339-339) ===
        private enum FollowerReplaceState { Idle, PendingCancel, Submitting, SubmitFailed }

// === BLOCK 2: FollowerReplaceSpec class (V12_002.cs L341-355) ===
        private class FollowerReplaceSpec
        {
            public FollowerReplaceState State;
            public string CancellingOrderId;
            public int    PendingQty;
            public double PendingLimitPrice;
            public double PendingStopPrice;
            public string AccountName;
            public string SignalName;
            public string MasterSignalName;
            public OrderAction EntryAction;    // captured from pos.Direction at spec creation
            public OrderType   EntryOrderType; // captured from fEntry.OrderType at spec creation
            public bool        IsStopType;     // true when EntryOrderType is StopMarket or StopLimit
            public string LastSubmitError;
        }

// === BLOCK 3: B3/B4 Suppression Gate (AccountOrders.cs L569-577) ===
            // Build 980 [Repair B]: B3/B4 suppression gate -- ignore trailing cancels for 2 seconds after CANCEL_ALL
            if (_fleetSuppressionMap.TryGetValue(acctName, out long suppressTicks))
            {
                if (DateTime.UtcNow.Ticks - suppressTicks < TimeSpan.TicksPerSecond * 2)
                {
                    Print($"[SUPPRESSION] B3/B4 Gate blocking trailing cancel for {order.Name} on {acctName}");
                    return;
                }
            }
