#!/usr/bin/env python3
"""
scripts/fsm_harness_split.py
Build 980 -- Section 7 Extractor Protocol
Reads FSM types verbatim from src/ and writes an audit reference.
"""
import sys
import os

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_MAIN = os.path.join(REPO_ROOT, "src", "V12_002.cs")
SRC_AO   = os.path.join(REPO_ROOT, "src", "V12_002.Orders.Callbacks.AccountOrders.cs")
OUT_FILE = os.path.join(REPO_ROOT, "tests", "V12.Tests", "FsmHarness.Extracted.cs")

# -------------------------------------------------------------------
# Source: V12_002.cs -- FollowerReplaceState enum + FollowerReplaceSpec class
# Lines are 1-indexed. Adjust if file changes.
FSM_ENUM_START  = 339   # private enum FollowerReplaceState {
FSM_ENUM_END    = 339
FSM_SPEC_START  = 341   # private class FollowerReplaceSpec
FSM_SPEC_END    = 355   # closing brace of FollowerReplaceSpec

# Source: AccountOrders.cs -- B3/B4 suppression gate block
SUPP_START = 569   # // Build 980 [Repair B]: B3/B4 suppression gate
SUPP_END   = 577   # closing brace of suppressTicks block
# -------------------------------------------------------------------


def read_lines_1indexed(path, start, end):
    """Read inclusive [start, end] lines (1-indexed) from file."""
    with open(path, "r", encoding="utf-8") as f:
        all_lines = f.readlines()
    return all_lines[start - 1 : end]


def count_occurrences(lines, pattern):
    return sum(1 for ln in lines if pattern in ln)


def main():
    print("[fsm_harness_split] Starting Section 7 extraction...")

    for path in [SRC_MAIN, SRC_AO]:
        if not os.path.exists(path):
            print(f"[fsm_harness_split] ERROR: Source file not found: {path}")
            sys.exit(1)

    # -- Extract FSM enum (single line)
    enum_lines = read_lines_1indexed(SRC_MAIN, FSM_ENUM_START, FSM_ENUM_END)
    # -- Extract FollowerReplaceSpec class
    spec_lines = read_lines_1indexed(SRC_MAIN, FSM_SPEC_START, FSM_SPEC_END)
    # -- Extract B3/B4 suppression gate
    supp_lines = read_lines_1indexed(SRC_AO, SUPP_START, SUPP_END)

    # Parity checks
    enum_ok = count_occurrences(enum_lines, "FollowerReplaceState") >= 1
    spec_ok = count_occurrences(spec_lines, "FollowerReplaceSpec") >= 1
    supp_ok = count_occurrences(supp_lines, "_fleetSuppressionMap") >= 1 or \
              count_occurrences(supp_lines, "suppressTicks") >= 1

    if not enum_ok:
        print("[fsm_harness_split] FAIL: FollowerReplaceState enum not found at expected lines")
        sys.exit(1)
    if not spec_ok:
        print("[fsm_harness_split] FAIL: FollowerReplaceSpec class not found at expected lines")
        sys.exit(1)
    if not supp_ok:
        print("[fsm_harness_split] FAIL: Suppression gate not found at expected lines")
        sys.exit(1)

    os.makedirs(os.path.dirname(OUT_FILE), exist_ok=True)

    header = (
        "// AUTO-GENERATED by scripts/fsm_harness_split.py (Section 7 -- Build 980)\n"
        "// THIS FILE IS AN AUDIT REFERENCE ONLY -- NOT COMPILED.\n"
        "// Verify against src/ originals before any harness changes.\n"
        "// -----------------------------------------------------------------------\n\n"
    )

    block1 = "// === BLOCK 1: FollowerReplaceState enum (V12_002.cs L{}-{}) ===\n".format(
        FSM_ENUM_START, FSM_ENUM_END)
    block2 = "\n// === BLOCK 2: FollowerReplaceSpec class (V12_002.cs L{}-{}) ===\n".format(
        FSM_SPEC_START, FSM_SPEC_END)
    block3 = "\n// === BLOCK 3: B3/B4 Suppression Gate (AccountOrders.cs L{}-{}) ===\n".format(
        SUPP_START, SUPP_END)

    with open(OUT_FILE, "w", encoding="utf-8") as f:
        f.write(header)
        f.write(block1)
        f.writelines(enum_lines)
        f.write(block2)
        f.writelines(spec_lines)
        f.write(block3)
        f.writelines(supp_lines)

    print(f"[fsm_harness_split] OK -- wrote audit reference to: {OUT_FILE}")
    print(f"  Enum lines   : {len(enum_lines)}")
    print(f"  Spec lines   : {len(spec_lines)}")
    print(f"  Gate lines   : {len(supp_lines)}")
    print("[fsm_harness_split] Section 7 parity check PASSED.")


if __name__ == "__main__":
    main()
