name: CodiumAI PR-Agent

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: CodiumAI PR-Agent
        uses: The-PR-Agent/pr-agent@6e6ef3fb8a40f3e7e94c180b14ec19e8f26ad83a  # pinned: 2024-12-stable
        continue-on-error: true
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_PATH: .pr_agent.toml
